// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {debate} from '../models';

export function AddAgentJS(arg1:main.AgentYAMLConfig):Promise<void>;

export function ContinueDebate(arg1:string):Promise<void>;

export function DeleteAgentJS(arg1:string):Promise<void>;

export function GetAgentConfigsJS():Promise<Array<main.AgentYAMLConfig>>;

export function GetAgents():Promise<Array<main.AgentInfoJS>>;

export function GetManager():Promise<debate.Manager>;

export function GetMessages():Promise<Array<main.MessageJS>>;

export function GetStatus():Promise<main.DebateStatusJS>;

export function OpenFile():Promise<string>;

export function ReloadAgents():Promise<void>;

export function ReorderAgentsJS(arg1:Array<string>):Promise<void>;

export function ResetDebate():Promise<void>;

export function SaveToFile(arg1:string,arg2:string):Promise<string>;

export function SetMode(arg1:string):Promise<void>;

export function StartDebate(arg1:string):Promise<void>;

export function StopDebate():Promise<void>;

export function TriggerAgent(arg1:string):Promise<void>;

export function TriggerNextAgent():Promise<void>;

export function UpdateAgentJS(arg1:string,arg2:main.AgentYAMLConfig):Promise<void>;
