// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAgentJS(arg1) {
  return window['go']['main']['App']['AddAgentJS'](arg1);
}

export function ContinueDebate(arg1) {
  return window['go']['main']['App']['ContinueDebate'](arg1);
}

export function DeleteAgentJS(arg1) {
  return window['go']['main']['App']['DeleteAgentJS'](arg1);
}

export function GetAgentConfigsJS() {
  return window['go']['main']['App']['GetAgentConfigsJS']();
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetManager() {
  return window['go']['main']['App']['GetManager']();
}

export function GetMessages() {
  return window['go']['main']['App']['GetMessages']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function ReloadAgents() {
  return window['go']['main']['App']['ReloadAgents']();
}

export function ReorderAgentsJS(arg1) {
  return window['go']['main']['App']['ReorderAgentsJS'](arg1);
}

export function ResetDebate() {
  return window['go']['main']['App']['ResetDebate']();
}

export function SaveToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveToFile'](arg1, arg2);
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}

export function StartDebate(arg1) {
  return window['go']['main']['App']['StartDebate'](arg1);
}

export function StopDebate() {
  return window['go']['main']['App']['StopDebate']();
}

export function TriggerAgent(arg1) {
  return window['go']['main']['App']['TriggerAgent'](arg1);
}

export function TriggerNextAgent() {
  return window['go']['main']['App']['TriggerNextAgent']();
}

export function UpdateAgentJS(arg1, arg2) {
  return window['go']['main']['App']['UpdateAgentJS'](arg1, arg2);
}
